var x = 'ALB ALBANY, NY ABQ ALBUQUERQUE, NM AMA AMARILLO, TX AUS AUSTIN, TX BWI BALTIMORE, MD BHM BIRMINGHAM, AL BOI BOISE, ID BOS BOSTON LOGAN, MA BUF BUFFALO, NY BUR BURBANK, CA CHS CHARLESTON, SC MDW CHICAGO (MIDWAY), IL CLE CLEVELAND, OH CMH COLUMBUS, OH CRP CORPUS CHRISTI, TX DAL DALLAS (LOVE), TX DEN DENVER, CO DTW DETROIT, MI ELP EL PASO, TX FLL FT LAUDERDALE, FL RSW FT MYERS, FL GSP GREENVILLE/SPARTANBURG, SC HRL HARLINGEN, TX BDL HARTFORD, CT HOU HOUSTON (HOBBY), TX IND INDIANAPOLIS, IN MCI KANSAS CITY, MO LAS LAS VEGAS, NV LIT LITTLE ROCK, AR ISP LONG ISLAND, NY LAX LOS ANGELES, CA SDF LOUISVILLE, KY LBB LUBBOCK, TX MHT MANCHESTER, NH MAF MIDLAND/ODESSA, TX MKE MILWAUKEE, WI MSP MINNEAPOLIS/ST PAUL, MN BNA NASHVILLE, TN MSY NEW ORLEANS, LA LGA NEW YORK (LA GUARDIA), NY EWR NEWARK, NJ ORF NORFORK, VA OAK OAKLAND, CA OKC OKLAHOMA CITY, OK OMA OMAHA, NE ONT ONTARIO, CA SNA ORANGE CO, CA MCO ORLANDO, FL ECP PANAMA CITY BEACH, FL PHL PHILADELPHIA, PA PHX PHOENIX, AZ PIT PITTSBURG, PA PDX PORTLAND, OR PVD PROVIDENCE, RI RDU RALEIGH/DURHAM, NC RNO RENO, NV SMF SACRAMENTO, CA SLC SALT LAKE CITY, UT SAT SAN ANTONIO, TX SAN SAN DIEGO, CA SFO SAN FRANCISCO, CA SJC SAN JOSE, CA SEA SEATTLE, WA GEG SPOKANE, WA STL ST LOUIS, MO TPA TAMPA, FL TUS TUCSON, AZ TUL TULSA, OK IAD WASHINGTON DC (DULLES) PBI WEST PALM BEACH, FL JAX Jacksonville, Fl ATL Atlanta, GA CAK Akron/Canton, OH CLT Charlotte, NC DAY Dayton, OH DCA Washington, DC DSM Des Moines, IA FNT Flint, MI GRR Grand Rapids, MI PNS Pensacola, FL PWM Portland, ME RIC Richmond, VA ROC Rochester, NY SJU San Juan, Puerto Rico ICT Wichita, KS MEM Memphis, TN BZE Belize City, Belize CUN Cancun, Mexico LIR Liberia, Costa Rica MBJ Montego Bay, Jamaica MEX Mexico City, Mexico NAS Nassau, Bahamas PUJ Punta Cana, Dominican Republic PVR Puerto Vallarta, Mexico SJD Cabo San Lucas/Los Cabos, Mexico AUA ARUBA, AW LGB LONG BEACH, CA MEX MEXICO CITY / D.F., MX PUJ PUNTA CANA, DO SJO SAN JOSE, COSTA RICA DCA WASHINGTON (REAGAN), DC';
var y = x.split(' ');

var z = y.filter(function(item) {
  return item.length === 3 && item !== 'SAN' && item !== 'LOS' && item !== 'Des' && item !== 'San' && item !== '(LA' && item !== 'CO,' && item !== 'NEW';
});

// Replace duplicate 'LAS with 'SAN' which was cut out by above.
z[28] = 'SAN';

console.log(z.length);
console.log(z);
console.log(z[z.length - 1]);

var allCodes = 
['ALB',
 'ABQ',
 'AMA',
 'AUS',
 'BWI',
 'BHM',
 'BOI',
 'BOS',
 'BUF',
 'BUR',
 'CHS',
 'MDW',
 'CLE',
 'CMH',
 'CRP',
 'DAL',
 'DEN',
 'DTW',
 'ELP',
 'FLL',
 'RSW',
 'GSP',
 'HRL',
 'BDL',
 'HOU',
 'IND',
 'MCI',
 'LAS',
 'SAN',
 'LIT',
 'ISP',
 'LAX',
 'SDF',
 'LBB',
 'MHT',
 'MAF',
 'MKE',
 'MSP',
 'BNA',
 'MSY',
 'LGA',
 'EWR',
 'ORF',
 'OAK',
 'OKC',
 'OMA',
 'ONT',
 'SNA',
 'MCO',
 'ECP',
 'PHL',
 'PHX',
 'PIT',
 'PDX',
 'PVD',
 'RDU',
 'RNO',
 'SMF',
 'SLC',
 'SAT',
 'SFO',
 'SJC',
 'SEA',
 'GEG',
 'STL',
 'TPA',
 'TUS',
 'TUL',
 'IAD',
 'PBI',
 'JAX',
 'ATL',
 'CAK',
 'CLT',
 'DAY',
 'DCA',
 'DSM',
 'FNT',
 'GRR',
 'PNS',
 'PWM',
 'RIC',
 'ROC',
 'SJU',
 'ICT',
 'MEM',
 'BZE',
 'CUN',
 'LIR',
 'MBJ',
 'MEX',
 'NAS',
 'PUJ',
 'PVR',
 'SJD',
 'AUA',
 'LGB',
 'MEX',
 'PUJ',
 'SJO',
 'DCA'] ;